// Extracts ABIs from the Foundry build (`contracts/out`) into typed `as const`
// modules under `src/abis/`. Run after `forge build`; commit the output so the
// Node CI job does not need Foundry.
//
//   node scripts/gen-abis.mjs
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, '../../../contracts/out');
const abiDir = resolve(here, '../src/abis');
mkdirSync(abiDir, { recursive: true });

/** contract name -> exported const name */
const CONTRACTS = {
  FloatComplianceRegistry: 'floatComplianceRegistryAbi',
  FloatAllowlistChecker: 'floatAllowlistCheckerAbi',
  FloatPolicyView: 'floatPolicyViewAbi',
  FloatSweepExecutor: 'floatSweepExecutorAbi',
  FloatUSTB: 'floatUstbAbi',
  FloatYieldReserve: 'floatYieldReserveAbi',
};

const exports = [];
for (const [contract, constName] of Object.entries(CONTRACTS)) {
  const artifactPath = resolve(outDir, `${contract}.sol`, `${contract}.json`);
  const artifact = JSON.parse(readFileSync(artifactPath, 'utf8'));
  const abi = artifact.abi;
  const file = `${constName.replace(/Abi$/, '')}.ts`;
  const banner = `// GENERATED by scripts/gen-abis.mjs from contracts/out/${contract}.sol — do not edit.\n`;
  writeFileSync(
    resolve(abiDir, file),
    `${banner}export const ${constName} = ${JSON.stringify(abi, null, 2)} as const;\n`,
  );
  exports.push(`export { ${constName} } from './${file.replace(/\.ts$/, '.js')}';`);
  console.log(`  ${contract} -> src/abis/${file} (${abi.length} entries)`);
}

writeFileSync(
  resolve(abiDir, '_generated.ts'),
  `// GENERATED by scripts/gen-abis.mjs — do not edit.\n${exports.join('\n')}\n`,
);
console.log('wrote src/abis/_generated.ts');
